name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

          host: 18.220.159.73
          username: ubuntu
          key: ${{ secrets.AWS }}
          script: |
            sudo su &&
            cd ../../var/zita &&
             git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
            git pull origin main &&
            sudo systemctl restart apache2.service
